import { describe, expect, it } from 'vitest';

import { getMockStore } from './mock-provider';

/**
 * Referential integrity of the mock fixtures. The demo store is edited by
 * hand and regenerated by scripts/generate-mock-json.mjs; a dangling id
 * surfaces as a blank card or a crash deep inside a page instead of a clear
 * failure, so assert the cross-references here.
 */
describe('mock data referential integrity', () => {
  const store = getMockStore();
  const employeeIds = new Set(store.employees.map((e) => e.id));
  const skillIds = new Set(store.skills.map((s) => s.id));
  const roleIds = new Set(store.roles.map((r) => r.id));
  const orgIds = new Set(store.organizations.map((o) => o.id));

  it('employee skills reference existing employees and skills', () => {
    for (const es of store.employeeSkills) {
      expect(employeeIds.has(es.employeeId), `employeeSkills ${es.id} → employee`).toBe(true);
      expect(skillIds.has(es.skillId), `employeeSkills ${es.id} → skill`).toBe(true);
    }
  });

  it('employees reference existing managers and organizations', () => {
    for (const e of store.employees) {
      if (e.managerId) {
        expect(employeeIds.has(e.managerId), `employee ${e.id} → manager`).toBe(true);
      }
      expect(orgIds.has(e.organizationId), `employee ${e.id} → organization`).toBe(true);
    }
  });

  it('growth plan items reference existing growth plans', () => {
    const planIds = new Set(store.growthPlans.map((p) => p.id));
    for (const item of store.growthPlanItems) {
      expect(planIds.has(item.growthPlanId), `growthPlanItem ${item.id} → plan`).toBe(true);
    }
  });

  it('opportunities reference existing roles', () => {
    for (const o of store.opportunities) {
      if (o.roleId) {
        expect(roleIds.has(o.roleId), `opportunity ${o.id} → role`).toBe(true);
      }
    }
  });

  it('decision outcomes reference existing workforce decisions', () => {
    const decisionIds = new Set(store.workforceDecisions.map((d) => d.id));
    for (const outcome of store.decisionOutcomes) {
      expect(decisionIds.has(outcome.decisionId), `outcome ${outcome.id} → decision`).toBe(true);
    }
  });

  it('role skills reference existing roles and skills', () => {
    for (const rs of store.roleSkills) {
      expect(roleIds.has(rs.roleId), `roleSkill → role ${rs.roleId}`).toBe(true);
      expect(skillIds.has(rs.skillId), `roleSkill → skill ${rs.skillId}`).toBe(true);
    }
  });
});
